/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/thalon.theme.ts
 * Command: astryx theme build src/theme/thalon.theme.ts --out src/theme/thalon-theme.css
 * Generated: 2026-07-25T14:42:26.527Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const thalonTheme: DefinedTheme;
