export {
  DERIVED_MS_PER_CHAR,
  MAX_DERIVED_CUE_MS,
  MIN_DERIVED_CUE_MS,
  derivePillarTimeline,
  derivedCueDurationMs,
  formatSrtTimestamp,
  pillarScriptToSrt,
  renderSrt,
  type PillarTimeline,
  type PillarTimelineCue,
} from "./srt";
export type {
  PillarRenderArtifacts,
  PillarRenderManifest,
  PillarRenderRequest,
  RenderTarget,
} from "./target";
export { createFakeRenderTarget, type FakeRenderTarget, type FakeRenderTargetDeps } from "./fake-target";
export { renderPillar, type RenderPillarDeps, type RenderPillarResult } from "./render";
export {
  COMPOSITION_GSAP_SRC,
  DEFAULT_CUE_MOTION,
  GENERIC_BRAND_STYLE,
  MOTION_EASING,
  PACING_SECONDS,
  PILLAR_COMPOSITION,
  PILLAR_COMPOSITION_PACING,
  assertSpecRenderable,
  compositionSpecFromDirectionExport,
  compositionSpecFromPillarManifest,
  defaultCueMotion,
  deriveBrandStyle,
  escapeHtml,
  hexToRgba,
  secondsLiteral,
  shiftHex,
  type CaptionWord,
  type CompositionAudio,
  type CompositionBrandStyle,
  type CompositionCue,
  type CompositionSpec,
  type CueNarrationClip,
} from "./composition";
export {
  GRAIN_STEP_MS,
  renderCompositionProject,
  type CompositionProject,
} from "./composition-project";
export {
  COMPOSITION_TRANSITIONS,
  DEFAULT_TRANSITION_CYCLE,
  TRANSITION_RECIPES,
  defaultTransition,
  type CompositionTransition,
  type TransitionProvenance,
  type TransitionRecipe,
} from "./composition-transitions";
export {
  HOOK_MAX_VISUAL_GAP_MS,
  MAX_VISUAL_GAP_MS,
  assertPacingDensity,
  planAccentPulses,
  type MotionEvent,
  type MotionEventKind,
  type MotionSchedule,
} from "./composition-pacing";
export {
  estimateCaptionWords,
  groupCaptionWords,
  planStat,
  type CaptionGroupPlan,
  type ScenePlan,
  type StatPlan,
} from "./composition-scene";
export { applyCueDirection, type CueDirective, type CueDirectives } from "./cue-direction";
export {
  CompositionLintError,
  FORBIDDEN_SCRIPT_PATTERNS,
  assertCompositionProjectSafe,
  assertCompositionSafe,
  hyperframesLinter,
  runCompositionLintGate,
  type CompositionLintFinding,
  type CompositionLinter,
} from "./composition-lint";
export {
  DEFAULT_TTS_VOICE,
  KOKORO_MODEL,
  createFakeNarrationDriver,
  createKokoroNarrationDriver,
  estimatedAligner,
  narrationCacheKey,
  wavDurationMs,
  withNarrationCache,
  type KokoroTtsRunner,
  type NarrationAligner,
  type NarrationAlignment,
  type NarrationArtifact,
  type NarrationDriver,
  type NarrationRequest,
} from "./narration";
export {
  DEFAULT_RENDER_TIMEOUT_MS,
  HYPERFRAMES_PRODUCER_PACKAGE,
  HyperframesRenderError,
  createHyperframesRenderTarget,
  type HyperframesFailureReason,
  type HyperframesProducerModule,
  type HyperframesRenderJob,
  type HyperframesTargetDeps,
  type RenderAudioBed,
  type RenderAudioBundle,
  type RenderAudioCue,
  type RenderAudioProvider,
} from "./hyperframes-target";
export {
  AUDIO_BED_FAMILY,
  AudioBedRejected,
  DEFAULT_BED_VOLUME,
  audioBedLicenseSchema,
  bedVolumeFromGainDb,
  configureProjectAudioBed,
  projectAudioBed,
  projectAudioBedSchema,
  readAudioBed,
  resolveProjectBed,
  storeAudioBed,
  withMusicBed,
  type AudioBedLicense,
  type BedOmission,
  type BedResolution,
  type ConfigureAudioBedInput,
  type ProjectAudioBed,
  type StoreAudioBedInput,
  type StoredAudioBed,
} from "./audio-bed";
export {
  RENDER_DRIVERS,
  RENDER_DRIVER_SWAP_PATH,
  getRenderTarget,
} from "./render-driver";
